import { once } from 'events'
import type { Writable } from 'stream'
import type { Row } from '@shared/types'
import type { DumpDialect } from './dump-dialect'

/** Rows per INSERT statement (spec §9: batched, never the whole table in memory). */
const DEFAULT_BATCH = 500

/** One table's contribution to a dump: its DDL and a stream of already-anonymized rows. */
export interface DumpTable {
  table: string
  /** Dialect-native CREATE TABLE (e.g. MySQL `SHOW CREATE TABLE`). */
  ddl: string
  /** Column order for INSERT tuples. */
  columns: string[]
  /**
   * Columns whose backing sequence should be reset after the data loads (`getSequenceColumns`).
   * Only consumed by dialects that need it (Postgres); ignored where the dialect has no
   * `resetSequence`. Must contain *only* genuinely sequence-backed columns — see
   * `postgresDumpDialect.resetSequence` for why a non-sequence column can't be no-op'd away.
   */
  sequenceColumns?: string[]
  /** Rows to write — already selected + anonymized upstream. Consumed once. */
  rows: AsyncIterable<Row>
}

export interface DumpPlan {
  /** Tables in topological (dependency) order — see `topologicalOrder`. */
  tables: DumpTable[]
  dialect: DumpDialect
  batchSize?: number
  /**
   * Emit `DROP TABLE IF EXISTS` for every table before the DDL, so the dump can be loaded over a
   * database that already holds a previous load of it (`Workspace.dropExistingTables`).
   */
  dropExistingTables?: boolean
}

/** Backpressure-aware write: wait for `drain` when the buffer is full. */
async function write(out: Writable, chunk: string): Promise<void> {
  throwIfErrored(out)
  if (!out.write(chunk)) await once(out, 'drain')
}

/** Rethrow a stream's error inside the writer's own promise, where the run's `catch` can see it. */
function throwIfErrored(out: Writable): void {
  if (out.errored) throw out.errored
}

/**
 * Keep an asynchronous stream error from becoming an uncaught exception.
 *
 * A file stream reports open and write failures (a full disk, a folder that vanished) as an `error`
 * event, often while the writer is awaiting the next source row rather than a `drain`. With no
 * listener at that moment Node throws it at the top level and the process exits, skipping the run's
 * failed-status and partial-file cleanup. The listener only absorbs the event; the error itself is
 * kept on `out.errored` and rethrown by the next `write`, row, or `finished()`.
 */
function guard(...outs: Writable[]): void {
  for (const out of outs) out.on('error', () => {})
}

function header(title: string): string {
  return `-- ${title}\n-- Generated by Masq\n\n`
}

/**
 * File header, the session settings, then the dialect's preamble (schema creation / search path),
 * if it has one.
 *
 * The session settings come first, before the preamble, on purpose: they tell the loading client
 * how to decode and how to parse every statement that follows, so anything emitted ahead of them
 * would be read under whatever the importing machine happens to be configured for. See
 * `DumpDialect.sessionSettings`.
 */
async function writeHeader(out: Writable, title: string, dialect: DumpDialect): Promise<void> {
  await write(out, header(title))
  if (dialect.sessionSettings) await write(out, `${dialect.sessionSettings}\n\n`)
  if (dialect.preamble) await write(out, `${dialect.preamble}\n\n`)
}

/** Closes a file: restores FK enforcement, then whatever `sessionSettings` changed. */
async function writeFooter(out: Writable, dialect: DumpDialect): Promise<void> {
  await write(out, `${dialect.enableForeignKeys}\n`)
  if (dialect.sessionRestore) await write(out, `${dialect.sessionRestore}\n`)
}

/**
 * The schema section: each table's DDL, in dependency order, each preceded by its own
 * `DROP TABLE IF EXISTS` when the workspace asks for one.
 *
 * **The drop sits with its CREATE rather than in a block of its own**, and that placement is the
 * whole point. MySQL commits every DDL statement as it runs and offers no way to roll them back, so
 * a file that drops all 77 tables up front and then fails on the first CREATE leaves the database
 * with nothing — which is exactly what happened on a reported import. Interleaved, the same failure
 * costs one table: everything before it has been recreated, everything after it is untouched.
 *
 * This reverses an earlier choice to emit all drops first (see `.memory/decisions.md`). That was
 * made to stop a Postgres `DROP … CASCADE` reaching a constraint the same file had just created —
 * but for that to happen a child would have to be dropped after its parent was created, which
 * dependency order already prevents except among circularly-referencing tables, and those cannot
 * load from a combined dump either way (the `ALTER TABLE … ADD CONSTRAINT` for the first table in
 * the cycle names a table the file has not created yet). So the cascade risk was theoretical where
 * the blast radius is not.
 */
async function writeDdlSection(
  out: Writable,
  tables: DumpTable[],
  dialect: DumpDialect,
  dropExisting: boolean
): Promise<void> {
  for (const t of tables) {
    await write(out, `--\n-- Table: ${t.table}\n--\n`)
    if (dropExisting) await write(out, `${dialect.dropTable(t.table)}\n`)
    // `SHOW CREATE TABLE` has no trailing semicolon; ensure exactly one.
    await write(out, `${t.ddl.trimEnd().replace(/;?$/, ';')}\n\n`)
  }
}

async function writeTableData(
  out: Writable,
  t: DumpTable,
  dialect: DumpDialect,
  batchSize: number
): Promise<void> {
  const columnList = t.columns.map((c) => dialect.id(c)).join(', ')
  const modifier = dialect.insertModifier ? `${dialect.insertModifier} ` : ''
  const prefix = `INSERT INTO ${dialect.id(t.table)} (${columnList}) ${modifier}VALUES\n`
  let batch: string[] = []
  let wroteAny = false

  const flush = async (): Promise<void> => {
    if (batch.length === 0) return
    await write(out, prefix + batch.join(',\n') + ';\n')
    batch = []
  }

  for await (const row of t.rows) {
    throwIfErrored(out)
    batch.push(`(${t.columns.map((c) => dialect.value(row[c])).join(', ')})`)
    wroteAny = true
    if (batch.length >= batchSize) await flush()
  }
  await flush()
  if (wroteAny) await write(out, '\n')
}

/**
 * Sequence resets, emitted after the data section (they read `MAX(col)`, so the rows must already
 * be in). No-op unless the dialect defines `resetSequence` — MySQL's AUTO_INCREMENT recovers from
 * the inserted values by itself, whereas a Postgres sequence keeps its pre-load value and the next
 * INSERT would collide on the primary key.
 */
async function writeSequenceResets(
  out: Writable,
  tables: DumpTable[],
  dialect: DumpDialect
): Promise<void> {
  const { resetSequence } = dialect
  if (!resetSequence) return

  const statements = tables.flatMap((t) =>
    (t.sequenceColumns ?? []).map((column) => resetSequence(t.table, column))
  )
  if (statements.length === 0) return

  await write(out, '--\n-- Sequence resets: next value = MAX(column)\n--\n')
  for (const statement of statements) await write(out, `${statement}\n`)
  await write(out, '\n')
}

async function writeDataSection(
  out: Writable,
  tables: DumpTable[],
  dialect: DumpDialect,
  batchSize: number
): Promise<void> {
  for (const t of tables) await writeTableData(out, t, dialect, batchSize)
}

/**
 * Combined dump (spec §9): one file, schema then data, wrapped in FK-check toggles so DDL with
 * forward/circular FK references and out-of-order inserts both load cleanly.
 */
export async function writeCombinedDump(out: Writable, plan: DumpPlan): Promise<void> {
  guard(out)
  const batchSize = Math.max(1, plan.batchSize ?? DEFAULT_BATCH)
  await writeHeader(out, 'Combined schema + data dump', plan.dialect)
  await write(out, `${plan.dialect.disableForeignKeys}\n\n`)
  // The FK toggle opened above covers the drops too — a DROP is refused while an FK points at the
  // table, and dependency order puts parents first, so the drops run child-last.
  await writeDdlSection(out, plan.tables, plan.dialect, !!plan.dropExistingTables)
  await writeDataSection(out, plan.tables, plan.dialect, batchSize)
  await writeSequenceResets(out, plan.tables, plan.dialect)
  await writeFooter(out, plan.dialect)
}

/**
 * Split dump (spec §9): a pure-DDL schema file (topological order) plus a re-runnable data file.
 * The data file toggles FK checks and TRUNCATEs every table in reverse dependency order before
 * inserting, so a team can re-apply just the data against a non-empty DB without PK conflicts.
 */
export async function writeSplitDump(
  schemaOut: Writable,
  dataOut: Writable,
  plan: DumpPlan
): Promise<void> {
  // Both at once: the data stream exists, and can fail to open, while the schema is still being written.
  guard(schemaOut, dataOut)
  const batchSize = Math.max(1, plan.batchSize ?? DEFAULT_BATCH)

  await writeHeader(schemaOut, 'Schema-only dump', plan.dialect)
  // The schema file carries no FK toggle when it only creates tables — they arrive in dependency
  // order, so nothing needs suppressing. Dropping is the case that does: an FK from a table outside
  // the dump set would refuse the DROP, and the toggle is the same one the data file uses.
  if (plan.dropExistingTables) await write(schemaOut, `${plan.dialect.disableForeignKeys}\n\n`)
  await writeDdlSection(schemaOut, plan.tables, plan.dialect, !!plan.dropExistingTables)
  if (plan.dropExistingTables) await write(schemaOut, `${plan.dialect.enableForeignKeys}\n`)
  if (plan.dialect.sessionRestore) await write(schemaOut, `${plan.dialect.sessionRestore}\n`)

  await writeHeader(dataOut, 'Data-only dump (re-runnable)', plan.dialect)
  await write(dataOut, `${plan.dialect.disableForeignKeys}\n\n`)
  for (const t of [...plan.tables].reverse()) {
    await write(dataOut, `${plan.dialect.truncate(t.table)}\n`)
  }
  await write(dataOut, '\n')
  await writeDataSection(dataOut, plan.tables, plan.dialect, batchSize)
  await writeSequenceResets(dataOut, plan.tables, plan.dialect)
  await writeFooter(dataOut, plan.dialect)
}
